[program:cedartoy]
command=python3 /opt/cedartoy/server.py
directory=/opt/cedartoy
autostart=true
autorestart=true
stderr_logfile=/var/log/cedartoy.err.log
stdout_logfile=/var/log/cedartoy.out.log
user=root
